const MESES_POR_AÑO = 12;
let nombre = prompt("Introduce tu nombre:");
var entradaEdad = prompt("Introduce tu edad:");
let edad = parseInt(entradaEdad, 10);
let peso = parseFloat(prompt("Introduce tu peso en kg:"));
let edadEnMeses = edad * MESES_POR_AÑO;
var gramos = peso * 1000;
let nombreVacio = nombre === "";
let edadPar = (edad % 2) === 0;
let resultadoLogico = nombreVacio || edadPar;
console.log("Nombre:", nombre);
console.log("Edad en meses:", edadEnMeses);
console.log("Peso en gramos:", gramos);
console.log("¿El nombre está vacío?", nombreVacio);
console.log("¿La edad es par?", edadPar);
console.log("Resultado de la combinación lógica (nombre vacío || edad par):", resultadoLogico);